input_model_name: Llama-2-7b-chat-hf
version: 4
seed: Null
batch_size: 2
split: train
downloaded: False

generation_kwargs:
  top_k: 40
  top_p: 0.8
  max_new_tokens: 35
  temperature: 0.9
  num_return_sequences: 4
  use_cache: True