input_model_name: Llama-2-7b-chat-hf
version: 5
seed: Null
batch_size: 2
split: train
downloaded: False

generation_kwargs:
  top_k: 50
  top_p: 0.95
  max_new_tokens: 50
  temperature: 0.9
  num_return_sequences: 4