dataset_name:  "allenai/c4"
subset: 'en'
key_column: "text"
splits: ['train', 'validation']
data_files: 
  train: "en/c4-train.0000*-of-01024.json.gz"
  validation:  "en/c4-validation.0000*-of-00008.json.gz"